[runtime]
; The emcee sampler, which uses the Goodman & Weare algorithm
sampler = test
root = ${PWD}
verbosity = standard


[test]
save_dir=output/cfhlens
fatal_errors=T


[pipeline]
modules = consistency  camb  load_nz  shear_shear  2pt  cfhtlens



[consistency]
file = utility/consistency/consistency_interface.py
verbose = F



[camb]
file = boltzmann/camb/camb_interface.py

; This means to calculate everything
; including matter power
mode = all
lmax = 2500

; You would set this to zero during an MCMC
; run to avoid too much line noise
feedback=2

; This means to get non-linear P(k), but
; not bother with non-linear CMB lensing
NonLinear = pk

; These choices values should be explored
; to check for convergence
kmax = 10.0
kmax_extrapolate = 500.0
nk = 100
zmin = 0.0
zmax = 3.0
nz = 100


[load_nz]
file = number_density/load_nz_fits/load_nz_fits.py
nz_file = likelihood/cfhtlens/cfhtlens_heymans13.fits
data_sets = SAMPLE


[shear_shear]
file = structure/projection/project_2d.py
shear-shear = sample-sample
verbose = T
ell_min = 20.0
ell_max = 10000.0
n_ell = 220

[cfhtlens]
file = likelihood/2pt/2pt_like.py
data_file = likelihood/cfhtlens/cfhtlens_heymans13.fits

like_name = cfhtlens
data_sets = xi_plus xi_minus

covariance_realizations = 1656

angle_range_xi_plus_1_1 = 2.0  999999.0
angle_range_xi_plus_1_2 = 2.0  999999.0
angle_range_xi_plus_2_1 = 2.0 999999.0
angle_range_xi_plus_2_2 = 2.0 999999.0
angle_range_xi_minus_1_1 = 2.0 999999.0
angle_range_xi_minus_1_2 = 2.0 999999.0

